model_list:
  - model_name: "gpt-4" # all requests where model not in your config go to this deployment
    litellm_params:
      model: openai/gpt-4 # set `openai/` to use the openai route

litellm_settings:
  success_callback: ["langtrace"]

environment_variables:
  LANGTRACE_API_KEY: "fake-api-key"
